# Generated by Django 5.2.4 on 2025-07-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_or_institution', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('experience_type', models.CharField(choices=[('work', 'Work Experience'), ('education', 'Education'), ('project', 'Project'), ('certification', 'Certification')], default='work', max_length=20)),
                ('skills', models.CharField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_date', 'order'],
            },
        ),
    ]
